version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p artifacts
      - zip -r artifacts/submitData.zip lambda/submitData
      - zip -r artifacts/dlqProcessor.zip lambda/dlqProcessor
      - zip -r artifacts/cleanup.zip lambda/cleanup

      - echo "Uploading Lambda artifacts to S3..."
      - aws s3 cp artifacts/ s3://$ArtifactBucketName/lambda/ --recursive

      - echo "Uploading CloudFormation templates to S3..."
      - aws s3 cp templates/ s3://$ArtifactBucketName/templates/ --recursive

      - echo "Deploying root stack..."
      - aws cloudformation deploy \
          --template-file templates/root.yaml \
          --stack-name devops-root-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              GitHubRepo=aws-devops-pipeline \
              GitHubOwner=asamimi2 \
              GitHubBranch=main \
              GitHubOAuthToken='{{resolve:secretsmanager:GitHubToken:SecretString}}' \
              ArtifactBucketName=$ArtifactBucketName \
              TemplateBaseURL=https://$ArtifactBucketName.s3.amazonaws.com/templates/
