version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p artifacts
      - zip -r artifacts/submitData.zip lambda/submitData
      - zip -r artifacts/dlqProcessor.zip lambda/dlqProcessor
      - zip -r artifacts/cleanup.zip lambda/cleanup

      - echo "Fetching artifact bucket name from bootstrap stack..."
      - export ARTIFACT_BUCKET=$(aws cloudformation describe-stacks \
          --stack-name devops-bootstrap-stack \
          --query "Stacks[0].Outputs[?OutputKey=='ArtifactBucketName'].OutputValue" \
          --output text)

      - echo "Uploading Lambda zips to S3..."
      - aws s3 cp artifacts/ s3://$ARTIFACT_BUCKET/lambda/ --recursive

      - echo "Uploading templates to S3..."
      - aws s3 cp templates/ s3://$ARTIFACT_BUCKET/templates/ --recursive --acl public-read

      - echo "Deploying root stack..."
      - aws cloudformation deploy \
          --template-file templates/root.yaml \
          --stack-name devops-root-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              GitHubRepo=aws-devops-pipeline \
              GitHubOwner=asamimi2 \
              GitHubBranch=main \
              GitHubOAuthToken='{{resolve:secretsmanager:GitHubToken:SecretString}}' \
              ArtifactBucketName=$ARTIFACT_BUCKET \
              TemplateBaseURL=https://$ARTIFACT_BUCKET.s3.amazonaws.com/templates/
