version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Setting environment variables..."
      - export ARTIFACT_BUCKET=$ARTIFACT_BUCKET
      - export STATIC_WEBSITE_BUCKET=$STATIC_WEBSITE_BUCKET

  build:
    commands:
      - echo "Preparing artifacts..."

      - mkdir -p artifacts/lambdas
      - mkdir -p artifacts/templates
      - mkdir -p artifacts/static-site

      # Zip Lambda functions
      - cd lambda/submitData && zip -r ../../artifacts/lambdas/submitData.zip . && cd -
      - cd lambda/dlqProcessor && zip -r ../../artifacts/lambdas/dlqProcessor.zip . && cd -
      - cd lambda/cleanup && zip -r ../../artifacts/lambdas/cleanup.zip . && cd -

      # Copy CloudFormation templates
      - cp templates/*.yaml artifacts/templates/

      # Copy static website files
      - cp static-website/index.html artifacts/static-site/
      - cp static-website/main.js artifacts/static-site/

artifacts:
  files:
    - artifacts/**/*  # Package the artifacts folder only
