version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Setting environment variable ARTIFACT_BUCKET..."
      - export ARTIFACT_BUCKET=$ARTIFACT_BUCKET  # Ensure ARTIFACT_BUCKET is set
      - export STATIC_WEBSITE_BUCKET=$STATIC_WEBSITE_BUCKET  # Ensure STATIC_WEBSITE_BUCKET is set

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p artifacts

      # Check if required directories exist
      - |
        for dir in lambda/submitData lambda/dlqProcessor lambda/cleanup; do
          if [ ! -d "$dir" ]; then
            echo "Directory $dir does not exist"; exit 1;
          fi
        done

      # Zip the Lambda functions
      - zip -r artifacts/submitData.zip lambda/submitData
      - zip -r artifacts/dlqProcessor.zip lambda/dlqProcessor
      - zip -r artifacts/cleanup.zip lambda/cleanup

      - echo "Uploading Lambda artifacts to S3..."
      - aws s3 cp artifacts/ s3://$ARTIFACT_BUCKET/lambda/ --recursive
      - aws s3 ls s3://$ARTIFACT_BUCKET/lambda/

      # Upload only index.html and main.js from static-website
      - echo "Uploading Static Website Files (index.html and main.js) to S3..."
      - aws s3 cp static-website/index.html s3://$STATIC_WEBSITE_BUCKET/index.html --recursive
      - aws s3 cp static-website/main.js s3://$STATIC_WEBSITE_BUCKET/main.js --recursive

      - aws s3 ls s3://$STATIC_WEBSITE_BUCKET/

      # Upload CloudFormation templates to Artifact Bucket
      - echo "Uploading CloudFormation templates to S3..."
      - aws s3 cp templates/ s3://$ARTIFACT_BUCKET/templates/ --recursive
      - aws s3 ls s3://$ARTIFACT_BUCKET/templates/

      - echo "Validating root stack template..."
      - aws cloudformation validate-template --template-body file://templates/root.yaml

      - echo "Deploying root stack with updated Lambda functions..."
      - aws cloudformation deploy --template-file templates/root.yaml --stack-name devops-root-stack --capabilities CAPABILITY_NAMED_IAM

artifacts:
  files:
    - '**/*'
