version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Setting environment variables..."
      - export ARTIFACT_BUCKET=$ARTIFACT_BUCKET
      - export STATIC_WEBSITE_BUCKET=$STATIC_WEBSITE_BUCKET
      - export VERSION=$(date +%s)
      - echo "Generated build version: $VERSION"

  build:
    commands:
      - echo "Preparing artifacts with version $VERSION..."
      - mkdir -p artifacts/lambdas artifacts/templates artifacts/static-site

      # Zip Lambda functions with VERSION in filename
      - cd lambda/submitData && zip -r ../../artifacts/lambdas/submitData-$VERSION.zip . && cd -
      - cd lambda/dlqProcessor && zip -r ../../artifacts/lambdas/dlqProcessor-$VERSION.zip . && cd -
      - cd lambda/cleanup && zip -r ../../artifacts/lambdas/cleanup-$VERSION.zip . && cd -

      # Copy templates
      - cp templates/*.yaml artifacts/templates/

      # Copy static website files
      - cp static-website/index.html artifacts/static-site/
      - cp static-website/main.js artifacts/static-site/

      - echo "Uploading artifacts to S3 bucket..."
      - aws s3 cp artifacts/lambdas/ s3://$ARTIFACT_BUCKET/lambda/ --recursive
      - aws s3 cp artifacts/templates/ s3://$ARTIFACT_BUCKET/templates/ --recursive
      - aws s3 cp artifacts/static-site/index.html s3://$STATIC_WEBSITE_BUCKET/index.html
      - aws s3 cp artifacts/static-site/main.js s3://$STATIC_WEBSITE_BUCKET/main.js

      - echo "Validating CloudFormation root template..."
      - aws cloudformation validate-template --template-body file://artifacts/templates/root.yaml

      - echo "Deploying CloudFormation root stack..."
      - aws cloudformation deploy --template-file artifacts/templates/root.yaml --stack-name devops-root-stack --capabilities CAPABILITY_NAMED_IAM --parameter-overrides Version=$VERSION

artifacts:
  files:
    - '**/*'
