version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p artifacts
      - zip -r artifacts/submitData.zip lambda/submitData
      - zip -r artifacts/dlqProcessor.zip lambda/dqlProcessor
      - zip -r artifacts/cleanup.zip lambda/cleanup

      - echo "Uploading Lambda artifacts to S3..."
      - aws s3 cp artifacts/ s3://$ARTIFACT_BUCKET/lambda/ --recursive

      - echo "Uploading CloudFormation templates to S3 (with public-read)..."
      - aws s3 cp templates/ s3://$ARTIFACT_BUCKET/templates/ --recursive --acl public-read

      - echo "Deploying root stack from remote template URLs..."
      - aws cloudformation deploy \
          --template-file templates/root.yaml \
          --stack-name devops-root-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              ArtifactBucketName=$ARTIFACT_BUCKET \
              TemplateBaseURL=https://$ARTIFACT_BUCKET.s3.amazonaws.com/templates/
