version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12

  build:
    commands:
      - echo "Zipping Lambda functions..."
      - mkdir -p artifacts
      - zip -r artifacts/submitData.zip lambda/submitData
      - zip -r artifacts/dlqProcessor.zip lambda/dlqProcessor
      - zip -r artifacts/cleanup.zip lambda/cleanup

      - echo "Deploying root stack to create buckets..."
      - aws cloudformation deploy \
          --template-file templates/root.yaml \
          --stack-name devops-root-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
              GitHubRepo=aws-devops-pipeline \
              GitHubOwner=asamimi2 \
              GitHubBranch=main \
              GitHubOAuthToken={{resolve:secretsmanager:GitHubToken:SecretString}}

      - echo "Retrieving newly created ArtifactBucket from stack outputs..."
      - export ARTIFACT_BUCKET=$(aws cloudformation describe-stacks \
          --stack-name devops-root-stack \
          --query "Stacks[0].Outputs[?OutputKey=='ArtifactBucketName'].OutputValue" \
          --output text)

      - echo "Uploading Lambda artifacts to S3..."
      - aws s3 cp artifacts/ s3://$ARTIFACT_BUCKET/lambda/ --recursive

      - echo "Uploading CloudFormation templates to S3..."
      - aws s3 cp templates/ s3://$ARTIFACT_BUCKET/templates/ --recursive --acl public-read
