AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge rule for scheduled cleanup tasks

Resources:

  DailyCleanupRule:
    Type: AWS::Events::Rule
    Properties:
      Name: DailyCleanupSchedule
      Description: Run cleanup Lambda function once a day
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Id: CleanupLambda
          Arn: !ImportValue CleanupFunctionArn

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue CleanupFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyCleanupRule.Arn
