AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge setup for event-driven architecture (fixed and aligned to architecture)

Parameters:
  StaticSiteBucketName:
    Type: String
    Description: Name of the static site S3 bucket (to pass to CleanupFunction)

Resources:
  # Custom Event Bus (optional if you want a separate bus, otherwise default bus is fine)
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: devops-event-bus

  # Scheduled Cleanup Event
  ScheduledCleanupRule:
    Type: AWS::Events::Rule
    Properties:
      Name: devops-scheduled-cleanup
      Description: "Scheduled trigger to cleanup old S3 objects nightly"
      ScheduleExpression: "cron(0 2 * * ? *)"  # every day at 2 AM UTC
      Targets:
        - Arn: !ImportValue CleanupFunctionArn
          Id: "CleanupFunctionTarget"
          Input: !Sub |
            {
              "bucket": "${StaticSiteBucketName}"
            }

  # Allow EventBridge to invoke CleanupFunction
  CleanupInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue CleanupFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledCleanupRule.Arn

Outputs:
  EventBusArn:
    Description: ARN of the EventBridge EventBus
    Value: !GetAtt EventBus.Arn
