AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge setup for event-driven architecture (fixed and aligned to architecture)

Resources:
  # Custom Event Bus (optional if you want a separate bus, otherwise default bus is fine)
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: devops-event-bus

  # (Optional) Scheduled Cleanup Event
  ScheduledCleanupRule:
    Type: AWS::Events::Rule
    Properties:
      Name: devops-scheduled-cleanup
      Description: "Scheduled trigger to cleanup old S3 objects nightly"
      ScheduleExpression: "cron(0 2 * * ? *)"  # every day at 2 AM UTC
      Targets:
        - Arn: !ImportValue CleanupFunctionArn
          Id: "CleanupFunctionTarget"
      EventBusName: !Ref EventBus

Outputs:
  EventBusArn:
    Description: ARN of the EventBridge EventBus
    Value: !GetAtt EventBus.Arn
