AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge setup for event-driven architecture

Resources:
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${AWS::StackName}-event-bus"

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-event-rule"
      EventPattern:
        source:
          - "aws.s3"
      Targets:
        - Arn: !GetAtt ProcessDataLambda.Arn
          Id: "ProcessDataLambdaTarget"

Outputs:
  EventBusArn:
    Description: ARN of the EventBridge EventBus
    Value: !GetAtt EventBus.Arn
