AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles and policies for the application

Parameters:
  StackPrefix:
    Type: String
    Description: A short prefix for stack resources (used for naming).
    Default: "devops-root-stack"

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "devops-LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "devops-LambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:GetObject
                Resource: "*"

  # CodePipeline Service Role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "devops-CodePipelineServiceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "devops-CodePipelinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - cloudformation:*
                  - lambda:InvokeFunction
                  - lambda:UpdateFunctionConfiguration
                  - lambda:InvokeFunction
                  - lambda:UpdateFunctionCode
                  - iam:PassRole
                  - iam:ListRoles
                  - codepipeline:StartPipelineExecution
                  - codepipeline:GetPipelineState
                  - codepipeline:PutActionRevision
                  - codepipeline:GetPipeline
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - config:PutEvaluations
                  - config:DescribeConfigRules
                Resource: "*"

  # CodeBuild Service Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "devops-CodeBuildServiceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "devops-CodeBuildPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  # S3 permissions for artifact storage and template access
                  - s3:*
                  # CloudFormation permissions to create, update, and delete stacks
                  - cloudformation:CreateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:UpdateStack
                  - cloudformation:ListStackResources
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:getTemplateSummary
                  - cloudformation:ValidateTemplate
                  # Lambda permissions for invocation and management
                  - lambda:CreateFunction
                  - lambda:InvokeFunction
                  - lambda:UpdateFunctionCode
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  # SQS permissions to create and manage queues
                  - sqs:CreateQueue
                  - sqs:DeleteQueue
                  - sqs:GetQueueUrl
                  - sqs:SetQueueAttributes
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  # EventBridge permissions to create and manage rules
                  - events:PutRule
                  - events:PutTargets
                  - events:DescribeRule
                  - events:DeleteRule
                  - events:PutEvents
                  - events:DeleteEventBus
                  - events:DeleteEvents
                  - events:ListTargetsByRule
                  - events:DescribeEvents
                  - events:DescribeEventBus
                  - events:ListEventBuses
                  - events:CreateEventBus
                  - events:RemoveTargets
                  # Monitoring permissions for CloudWatch and log management
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DeleteLogGroup
                  - logs:DeleteLogStream
                  # CodePipeline permissions to start, stop, and manage the pipeline
                  - codepipeline:CreatePipeline
                  - codepipeline:DeletePipeline
                  - codepipeline:StartPipelineExecution
                  - codepipeline:GetPipelineState
                  - codepipeline:PutActionRevision
                  - codepipeline:PutApprovalResult
                  - codepipeline:GetPipeline
                  - codepipeline:ListPipelines 
                  # Secrets Manager permissions to manage secrets
                  - secretsmanager:GetSecretValue
                  # IAM permissions for role management
                  - iam:DeleteRolePolicy
                  - iam:GetRole
                  - iam:GetRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:AttachRolePolicy
                  - iam:PassRole
                  - iam:PutRolePolicy
                  # CodeBuild specific permissions
                  - codebuild:CreateProject
                  - codebuild:DeleteProject
                  - codebuild:DescribeProjects
                  - codebuild:UpdateProject
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  # CloudWatch permissions for alarms
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DeleteAlarms
                  # SNS permissions for alarm notification
                  - sns:CreateTopic
                  - sns:Subscribe
                  - sns:SetTopicAttributes
                  - sns:GetTopicAttributes
                  - sns:DeleteTopic
                  # API Gateway permissions for creating and managing APIs
                  - apigateway:CreateRestApi
                  - apigateway:CreateResource
                  - apigateway:CreateMethod
                  - apigateway:CreateMethodResponse
                  - apigateway:CreateIntegration
                  - apigateway:CreateDeployment
                  - apigateway:DeleteRestApi
                  - apigateway:DeleteResource
                  - apigateway:DeleteMethod
                  - apigateway:DeleteMethodResponse
                  - apigateway:DeleteIntegration
                  - apigateway:DeleteDeployment
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:GET
                  - apigateway:DELETE
                  - apigateway:PATCH
                Resource: "*"

Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRoleArn

  CodePipelineServiceRoleArn:
    Description: ARN of the CodePipeline service role
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: CodePipelineServiceRoleArn

  CodeBuildServiceRoleArn:
    Description: ARN of the CodeBuild service role
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: CodeBuildServiceRoleArn
