AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda functions and IAM roles

Resources:
  # Submit Data Lambda Function
  SubmitDataFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SubmitDataFunction
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue ArtifactBucketName
        S3Key: lambda/submitData.zip
      Timeout: 10
      Environment:
        Variables:
          QUEUE_URL: !ImportValue MyQueueUrl
          BUCKET_NAME: !ImportValue StaticSiteBucketName

  # DLQ Processor Lambda Function
  DLQProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DLQProcessorFunction
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue ArtifactBucketName
        S3Key: lambda/dlqProcessor.zip
      Timeout: 10

  # Cleanup Lambda Function
  CleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CleanupFunction
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !ImportValue LambdaExecutionRoleArn
      Code:
        S3Bucket: !ImportValue ArtifactBucketName
        S3Key: lambda/cleanup.zip
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !ImportValue StaticSiteBucketName  # Attach StaticSiteBucketName from the root stack

Outputs:
  SubmitDataFunctionArn:
    Value: !GetAtt SubmitDataFunction.Arn
    Export:
      Name: SubmitDataFunctionArn

  CleanupFunctionArn:
    Value: !GetAtt CleanupFunction.Arn
    Export:
      Name: CleanupFunctionArn
