AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring resources for application

Resources:
  AlarmNotification:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Alarm Notification
      Subscription:
        - Protocol: email
          Endpoint: "aarash.samimi@cdw.com"

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "ErrorAlarm"
      MetricName: "Errors"
      Namespace: "AWS/Lambda"
      Statistic: "Sum"
      Period: 60
      Threshold: 1
      ComparisonOperator: "GreaterThanThreshold"
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref AlarmNotification

Outputs:
  AlarmArn:
    Description: ARN of the CloudWatch alarm
    Value: !GetAtt CloudWatchAlarm.Arn