AWSTemplateFormatVersion: '2010-09-09'
Description: Full CI/CD Pipeline for Serverless App Deployment

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., aws-devops-pipeline)
    Default: "aws-devops-pipeline"

  GitHubOwner:
    Type: String
    Description: GitHub username or organization
    Default: "asamimi2"

  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to monitor

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token stored in Secrets Manager
    Default: "{{resolve:secretsmanager:GitHubToken:SecretString}}"

Resources:
  # CodeBuild Project for building the app
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CodeBuildProject
      Description: CodeBuild Project for Building the App
      ServiceRole: !ImportValue CodeBuildServiceRoleArn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !ImportValue ArtifactBucketName
          - Name: STATIC_WEBSITE_BUCKET
            Value: !ImportValue StaticSiteBucketName
          - Name: GitHubOAuthToken
            Value: !Ref GitHubOAuthToken
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepo}"
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
      Artifacts:
        Type: S3
        Location: !ImportValue ArtifactBucketName
        Packaging: ZIP
        Name: build-output

  # CodePipeline Pipeline
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken

        - Name: Build
          Actions:
            - Name: CodeBuild_Action
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: DeployStaticWebsite
          Actions:
            - Name: Deploy_Static_Website
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                BucketName: !ImportValue StaticSiteBucketName
                Extract: true
                # Deploy ONLY static site files from 'artifacts/static-site/'
                ObjectKey: artifacts/static-site/

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
    Description: The CodeBuild project used for the CI/CD pipeline.

  PipelineName:
    Value: !Ref Pipeline
    Description: The pipeline for the CI/CD process.

  CodePipelineArn:
    Value: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:pipeline/${Pipeline}
    Description: The ARN of the CodePipeline pipeline.
