AWSTemplateFormatVersion: '2010-09-09'
Description: Full CI/CD Pipeline for Serverless App Deployment

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., aws-devops-pipeline)

  GitHubOwner:
    Type: String
    Description: GitHub username or organization

  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to monitor for changes

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token stored in Secrets Manager

Resources:
  # CodeBuild Project for building the app
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: CodeBuildProject
      Description: CodeBuild Project for Building the App
      ServiceRole: !ImportValue CodePipelineServiceRoleArn  # Import the role ARN
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !ImportValue ArtifactBucketName
          - Name: GitHubOAuthToken
            Value: !Ref GitHubOAuthToken
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitHubOwner}/${GitHubRepo}"
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
      Artifacts:
        Type: S3
        Location: !ImportValue ArtifactBucketName
        Packaging: ZIP
        Name: build-output

  # CodePipeline Pipeline that orchestrates all stages
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !ImportValue CodePipelineServiceRoleArn  # Import the role ARN
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
        - Name: Build
          Actions:
            - Name: CodeBuild_Action
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: DeployStaticWebsite
          Actions:
            - Name: Deploy_Static_Website
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                BucketName: !ImportValue StaticSiteBucketName
                Extract: "true"

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
    Description: The CodeBuild project used for the CI/CD pipeline.
  
  PipelineName:
    Value: !Ref Pipeline
    Description: The pipeline for the CI/CD process.
  
  CodePipelineArn:
    Value: !GetAtt Pipeline.Arn
    Description: The ARN of the CodePipeline pipeline.