AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and create required S3 buckets

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., aws-devops-pipeline)
    Default: "aws-devops-pipeline"

  GitHubOwner:
    Type: String
    Description: GitHub username or organization
    Default: "asamimi2"

  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to monitor

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token stored in Secrets Manager
    Default: "{{resolve:secretsmanager:GitHubToken:SecretString}}"

  ArtifactBucketName:
    Type: String
    Description: Name of the artifact bucket exported from the bootstrap stack
    Default: "devops-bootstrap-stack-artifacts"

Resources:
  # Static Site Stack Reference
  StaticSiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/s3.yaml"
  
  # SQS Stack
  SQSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StaticSiteStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/sqs.yaml"

  # === Lambda Stack ===
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - SQSStack
      - StaticSiteStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/lambda.yaml"
      Parameters:
        ArtifactBucketName: !Ref ArtifactBucketName
        StaticSiteBucketName: !ImportValue StaticSiteBucket
        UserQueueUrl: !ImportValue UserQueueUrl

  # === EventBridge Stack ===
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    # DependsOn: 
    #   - SQSStack
    #   - StaticSiteBucket
    #   - LambdaStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/eventbridge.yaml"

  # === Monitoring Stack ===
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    # DependsOn: 
    #   - SQSStack
    #   - StaticSiteBucket
    #   - LambdaStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/monitoring.yaml"

  # === Pipeline Stack ===
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - StaticSiteStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/pipeline.yaml"
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubOAuthToken: !Ref GitHubOAuthToken
        ArtifactBucketName: !Ref ArtifactBucketName
        StaticSiteBucketName: !ImportValue StaticSiteBucket
