AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack that orchestrates all resources and pipelines

Parameters:
  GitHubRepo:
    Type: String
  GitHubOwner:
    Type: String
  GitHubBranch:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true

Resources:

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ArtifactBucket
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}pipeline.yaml"
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubOAuthToken: !Ref GitHubOAuthToken
        ArtifactBucketName: !Ref ArtifactBucket
        StaticSiteBucketName: !Ref StaticSiteBucket

  # Add other stacks as needed
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}lambda.yaml"

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
  StaticSiteBucketName:
    Value: !Ref StaticSiteBucket
