AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and resources

Parameters:
  GitHubRepo:
    Type: String
  GitHubOwner:
    Type: String
  GitHubBranch:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true

Resources:

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ArtifactBucket
    Properties:
      TemplateURL: !Sub "https://${AWS::StackName}-artifacts.s3.${AWS::Region}.amazonaws.com/templates/pipeline.yaml"
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubOAuthToken: !Ref GitHubOAuthToken

Outputs:

  StaticSiteBucketName:
    Value: !Ref StaticSiteBucket
    Export:
      Name: StaticSiteBucketName

  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: ArtifactBucketName
