AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks

Parameters:
  ArtifactBucketName:
    Type: String
    Description: S3 bucket for artifacts and templates

  TemplateBaseURL:
    Type: String
    Description: Base S3 URL where templates are stored (e.g., https://bucket-name.s3.amazonaws.com/templates/)

Resources:

  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}pipeline.yaml"
      Parameters:
        GitHubRepo: aws-devops-pipeline
        GitHubOwner: asamimi2
        GitHubBranch: main
        GitHubOAuthToken: "{{resolve:ssm:/github/token}}"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}lambda.yaml"

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}s3.yaml"

  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}eventbridge.yaml"

  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}sqs.yaml"

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}monitoring.yaml"