AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and create required S3 buckets

Resources:
  # IAM Stack Reference
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/iam.yaml"

  # SQS Stack
  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/sqs.yaml"

  # Lambda Stack
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IAMStack
      - SQSStack
      - APIGatewayStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/lambda.yaml"

  # EventBridge Stack
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - SQSStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/eventbridge.yaml"

  # Monitoring Stack
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - SQSStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/monitoring.yaml"

  # Pipeline Stack
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IAMStack
      - SQSStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/pipeline.yaml"