AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and create required S3 buckets

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., aws-devops-pipeline)
    Default: "aws-devops-pipeline"

  GitHubOwner:
    Type: String
    Description: GitHub username or organization
    Default: "asamimi2"

  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to monitor

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token stored in Secrets Manager
    Default: "{{resolve:secretsmanager:GitHubToken:SecretString}}"

  ArtifactBucketName:
    Type: String
    Description: Name of the artifact bucket exported from the bootstrap stack
    Default: !ImportValue ArtifactBucketName

Resources:
  # Static Site Bucket
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "devops-root-stack-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  # Static Site Bucket Policy
  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: StaticSiteBucket
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${StaticSiteBucket}/*"

  # === SQS Stack ===
  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/sqs.yaml"

  # === Lambda Stack ===
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [SQSStack]
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/lambda.yaml"

  # === EventBridge Stack ===
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [LambdaStack]
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/eventbridge.yaml"

  # === Monitoring Stack ===
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [LambdaStack]
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/monitoring.yaml"

  # === Pipeline Stack ===
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - StaticSiteBucket
      - SQSStack
    Properties:
      TemplateURL: !Sub "https://${ArtifactBucketName}.s3.${AWS::Region}.amazonaws.com/templates/pipeline.yaml"
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubOAuthToken: !Ref GitHubOAuthToken
        ArtifactBucketName: !Ref ArtifactBucketName
        StaticSiteBucketName: !Ref StaticSiteBucket

Outputs:
  StaticSiteBucketName:
    Description: Name of the static site bucket
    Value: !Ref StaticSiteBucket
    Export:
      Name: StaticSiteBucketName
