AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and create required buckets

Parameters:
  TemplateBaseURL:
    Type: String
    Description: Base S3 URL where templates are stored (e.g., https://your-bucket.s3.amazonaws.com/templates/)

Resources:

  # --- S3 Buckets for Artifacts & Frontend ---
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"

  # --- Sub-stacks ---
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ArtifactBucket
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}pipeline.yaml"
      Parameters:
        GitHubRepo: aws-devops-pipeline
        GitHubOwner: asamimi2
        GitHubBranch: main
        GitHubOAuthToken: "{{resolve:secretsmanager:GitHubToken:SecretString}}"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}lambda.yaml"

  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}eventbridge.yaml"

  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}sqs.yaml"

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBaseURL}monitoring.yaml"

Outputs:

  StaticSiteBucketName:
    Description: Name of the static site hosting bucket
    Value: !Ref StaticSiteBucket
    Export:
      Name: StaticSiteBucketName

  ArtifactBucketName:
    Description: Name of the artifact storage bucket
    Value: !Ref ArtifactBucket
    Export:
      Name: ArtifactBucketName