AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to deploy complete CI/CD pipeline and serverless application using nested local templates

Resources:

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/s3.yaml

  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/sqs.yaml

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/lambda.yaml
      Parameters:
        ArtifactBucketName: !ImportValue ArtifactBucketName

  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/monitoring.yaml

  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/eventbridge.yaml