AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack to orchestrate all sub-stacks and create required S3 buckets

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g., aws-devops-pipeline)
    Default: "aws-devops-pipeline"

  GitHubOwner:
    Type: String
    Description: GitHub username or organization
    Default: "asamimi2"

  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to monitor

  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token stored in Secrets Manager
    Default: "{{resolve:secretsmanager:GitHubToken:SecretString}}"

Resources:
  # IAM Stack Reference
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/iam.yaml"

  # Static Site Stack Reference
  StaticSiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/s3.yaml"

  # SQS Stack
  SQSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StaticSiteStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/sqs.yaml"

  # Lambda Stack
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IAMStack
      - SQSStack
      - StaticSiteStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/lambda.yaml"

  # EventBridge Stack
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - SQSStack
      - StaticSiteStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/eventbridge.yaml"

  # Monitoring Stack
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - SQSStack
      - StaticSiteStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/monitoring.yaml"

  # Pipeline Stack
  PipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IAMStack
      - SQSStack
      - StaticSiteStack
      - LambdaStack
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !ImportValue ArtifactBucketName
          - ".s3."
          - !Ref "AWS::Region"
          - ".amazonaws.com/templates/pipeline.yaml"
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubOwner: !Ref GitHubOwner
        GitHubBranch: !Ref GitHubBranch
        GitHubOAuthToken: !Ref GitHubOAuthToken