AWSTemplateFormatVersion: '2010-09-09'
Description: Static website setup in a separate stack.

Resources:
  # Static Site Bucket
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "devops-root-stack-frontend"
      WebsiteConfiguration:
        IndexDocument: static-site/index.html
        ErrorDocument: static-site/index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  # Static Site Bucket Policy
  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: StaticSiteBucket
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${StaticSiteBucket}/static-site/*"

Outputs:
  StaticSiteBucketName:
    Description: Name of the static site bucket
    Value: !Ref StaticSiteBucket
    Export:
      Name: StaticSiteBucketName