AWSTemplateFormatVersion: '2010-09-09'
Description: SQS Stack to create a Simple Queue Service (SQS) Queue

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: devops-sqs-queue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 86400  # 1 day in seconds
      DelaySeconds: 0
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn
        maxReceiveCount: 5  # Messages that are received and not deleted will be moved to DLQ after 5 attempts

  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: devops-sqs-dlq
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600  # 14 days in seconds

Outputs:
  MyQueueUrl:
    Description: The URL of the SQS queue
    Value: !Ref MyQueue
    Export:
      Name: UserQueueUrl  # This export name should match the name you're using in the root stack
